import { TUTORIAL_TARGETS } from './tutorialRegistry.js'

export const TUTORIAL_VERSION = 'tutorial-v3-ground-up'

export const E2E_TUTORIAL_UID = 'phase23p-e2e-organizer'

export const TARGET_UIDS = [
  'WcDU2jmbopdAgDlMMWvD3TkqqbC3',
  'WM2UOQtSeuOglCI5uMZQKrYYqP53',
  E2E_TUTORIAL_UID,
]

export const guidedTutorialSteps = [
  {
    id: 'working-event',
    title: 'Working Event',
    routeId: 'dashboard',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.workingEventSelector,
    area: 'Event scope',
    content: 'The Working Event tells you which event every organizer page is currently using.',
    when: 'Check it before changing guests, payments, tickets, Operations, or reports.',
    action: 'Confirm the selected event or use Change event to switch contexts.',
    example: 'Before reviewing payments, confirm CODEX_TEST is selected so CPB data stays untouched.',
    affects: 'This controls which event-scoped records the rest of the app loads.',
  },
  {
    id: 'overview',
    title: 'Overview',
    routeId: 'dashboard',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.overviewPrimaryMetrics,
    area: 'Daily starting point',
    content: 'Overview summarizes the active event, key counts, money snapshot, capacity, and attention items.',
    when: 'Open it first when deciding what needs work today.',
    action: 'Use the metrics and Needs Attention list to choose the next task.',
    example: 'If missing tickets appear here, move to Tickets instead of scanning registration rows manually.',
    affects: 'It points you into Events, Payments, Operations, Tickets, and Reports without duplicating those pages.',
  },
  {
    id: 'create-event',
    title: 'Create Event',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventsCreateButton,
    area: 'Event setup',
    content: 'Create one workspace per gathering so registrations, tickets, money, and reporting stay scoped.',
    when: 'Use it when a new birthday, wedding, workshop, tasting, or private event needs planning.',
    action: 'Open the form, enter event basics, and cancel if you are only practicing.',
    example: 'A bridal shower gets its own date, venue, capacity, registration settings, and Operations records.',
    affects: 'The event becomes available as a Working Event for every other module.',
  },
  {
    id: 'event-category',
    title: 'Event Category',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventCategorySelector,
    area: 'Event setup',
    content: 'Event category keeps planning language generic and helps suggest useful defaults.',
    when: 'Review it when an event is not a standard ticketed food event.',
    action: 'Choose the closest category, then review the suggested setup.',
    example: 'A workshop can surface planning prompts that differ from a private tasting.',
    affects: 'Category affects planning prompts without rewriting old event records automatically.',
  },
  {
    id: 'event-capabilities',
    title: 'Optional Event Capabilities',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventCapabilities,
    area: 'Event setup',
    content: 'Capabilities describe which optional planning prompts are useful for the event.',
    when: 'Use them when vendors, sponsors, school participation, or special logistics apply.',
    action: 'Review or override capabilities before saving the event.',
    example: 'A cultural experience may need sponsor and supplier tracking while a small private event may not.',
    affects: 'Capabilities guide planning sections without turning on unrelated modules.',
  },
  {
    id: 'event-planning',
    title: 'Event Planning',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventPlanning,
    area: 'Planning workspace',
    content: 'Events holds setup, readiness, planning tasks, and organizer next steps.',
    when: 'Use it while preparing the event before event day.',
    action: 'Track readiness items, tasks, venue details, and planning notes.',
    example: 'Add a venue-access task and mark ticket process ready when confirmed.',
    affects: 'Planning status feeds the Overview and Reports readiness view.',
  },
  {
    id: 'registrations',
    title: 'Guests & Registrations',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsSummary,
    area: 'Guest records',
    content: 'Registrations are booking records; guests are counted from persons attending and attendee names.',
    when: 'Use this page to add, correct, filter, and review registration records.',
    action: 'Search, filter, open a record, or start a new registration when approved.',
    example: 'One registration can represent a four-person group booking.',
    affects: 'Registration data feeds Payments, Tickets, Check-In, and Reports.',
  },
  {
    id: 'add-registration',
    title: 'Add Registration',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsAddButton,
    area: 'Guest records',
    content: 'Adding a registration creates the source booking record for guests, tickets, and payments.',
    when: 'Use it only when you have an approved registration to enter.',
    action: 'Open the form, review required fields, and cancel during practice.',
    example: 'Add a buyer, contact method, persons attending, and payment status after confirmation.',
    affects: 'New registrations can change guest count, payment follow-up, ticket readiness, and check-in lists.',
  },
  {
    id: 'registration-filters',
    title: 'Registration Filters',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationFilters,
    area: 'Guest records',
    content: 'Filters help isolate unpaid, incomplete, duplicate, or ticket-related registration work.',
    when: 'Use filters before editing records or sending follow-up messages.',
    action: 'Choose a supported filter, review the list, then clear it when done.',
    example: 'Filter unpaid registrations before building a payment reminder.',
    affects: 'Filtered context can inform Message Builder and Reports without changing records.',
  },
  {
    id: 'payments',
    title: 'Registration Payments',
    routeId: 'payments',
    pathname: '/payments',
    targetId: TUTORIAL_TARGETS.paymentsSummary,
    area: 'Payment review',
    content: 'Payments covers registration charges, received amounts, balances, methods, proof, and follow-up.',
    when: 'Use it when cleaning registration finance data or deciding who needs follow-up.',
    action: 'Review payment status and evidence before making any financial change.',
    example: 'A paid registration missing a method is internal cleanup, not a reminder audience.',
    affects: 'Payment review stays separate from the event-level Operations Ledger.',
  },
  {
    id: 'tickets',
    title: 'Tickets',
    routeId: 'tickets',
    pathname: '/tickets',
    targetId: TUTORIAL_TARGETS.ticketsReadiness,
    area: 'Ticket preparation',
    content: 'Tickets prepares ticket codes and QR access for the selected Working Event.',
    when: 'Use it before event day to find missing ticket codes and review readiness.',
    action: 'Assign or review ticket codes using the existing ticket workflow.',
    example: 'The QR payload remains GSV:TICKET:{ticketCode}, not private guest or payment data.',
    affects: 'Tickets feed Check-In and scanner lookup.',
  },
  {
    id: 'check-in',
    title: 'Check-In',
    routeId: 'check-in',
    pathname: '/check-in',
    targetId: TUTORIAL_TARGETS.checkInSearch,
    area: 'Event day',
    content: 'Check-In records attendance from deliberate organizer or scanner action.',
    when: 'Use it at the door to find guests, scan ticket codes, and confirm attendance.',
    action: 'Search or scan, then use the explicit Check In control only when the guest arrives.',
    example: 'Scanning finds the ticket first; a separate action records attendance.',
    affects: 'Check-In updates attendance reporting, not registration payment totals.',
  },
  {
    id: 'operations',
    title: 'Operations',
    routeId: 'operations',
    pathname: '/operations',
    targetId: TUTORIAL_TARGETS.operationsLedgerSummary,
    area: 'Event-level ledger',
    content: 'Operations tracks sponsor income, supplier payments, expenses, refunds, commitments, and adjustments.',
    when: 'Use it for event-level obligations, not ordinary guest registration payments.',
    action: 'Review summaries and ledger records before adding or editing entries.',
    example: 'Record venue cost here; do not duplicate a guest payment as Operations income.',
    affects: 'Operations reporting remains separate from Registration Payments.',
  },
  {
    id: 'partners',
    title: 'Partners, Suppliers, and Sponsors',
    routeId: 'operations',
    pathname: '/operations',
    targetId: TUTORIAL_TARGETS.partnersSponsors,
    area: 'Event relationships',
    content: 'Partners and suppliers make external commitments visible without treating them as guest payments.',
    when: 'Use them to track people, companies, obligations, and sponsorship status.',
    action: 'Inspect existing commitments or open the relevant form when you have a real update.',
    example: 'Track a sponsor as requested, confirmed cash, or in-kind support.',
    affects: 'These records can drive Operations follow-up and event readiness.',
  },
  {
    id: 'communications',
    title: 'Message Builder',
    routeId: 'communications',
    pathname: '/communications',
    targetId: TUTORIAL_TARGETS.messageBuilder,
    area: 'Copy-only messaging',
    content: 'Message Builder creates, personalizes, previews, and copies messages. It does not send automatically.',
    when: 'Use it when you need text for WhatsApp, email, or another external tool.',
    action: 'Choose a template, review recipients, copy the message, and send outside the app.',
    example: 'Build an unpaid-balance reminder, then manually send it through your chosen channel.',
    affects: 'Message copy can reflect registrations and payments without changing records.',
  },
  {
    id: 'reports',
    title: 'Reports',
    routeId: 'reports',
    pathname: '/event-review',
    targetId: TUTORIAL_TARGETS.reportsSummary,
    area: 'Read-only review',
    content: 'Reports summarizes follow-up, registration payments, Operations, attendance, and event status.',
    when: 'Use it for current review, closeout, or historical reference.',
    action: 'Read sections carefully; do not expect save, reconcile, or delete controls here.',
    example: 'Review Registration Payments and Operations separately before discussing financial results.',
    affects: 'Reports helps validate work done elsewhere without changing event records.',
  },
  {
    id: 'imports',
    title: 'Import Center',
    routeId: 'imports',
    pathname: '/imports',
    targetId: TUTORIAL_TARGETS.importCenterSource,
    area: 'Preview-first import',
    content: 'Import Center brings in CSV, pasted rows, and supported spreadsheets through review before saving.',
    when: 'Use it when data starts in Google Forms, Sheets, Excel, or another system.',
    action: 'Choose a source, map fields, preview, check duplicates, then import only approved rows.',
    example: 'Upload a Google Forms CSV and review all detected fields before committing registrations.',
    affects: 'Imports can create registration records only after explicit confirmation.',
  },
  {
    id: 'settings',
    title: 'Settings',
    routeId: 'settings',
    pathname: '/settings',
    targetId: TUTORIAL_TARGETS.settingsTourReplay,
    area: 'Workspace configuration',
    content: 'Settings contains practical defaults, access summaries, scanner links, and tutorial replay.',
    when: 'Use it to review configuration rather than daily event work.',
    action: 'Find replay, review account category, or copy supported scanner links.',
    example: 'Replay this tutorial from Settings after the first automatic run is complete.',
    affects: 'Settings supports the workspace without changing event financial records.',
  },
  {
    id: 'system-qa',
    title: 'System QA and Help',
    routeId: 'system-qa',
    pathname: '/qa',
    targetId: TUTORIAL_TARGETS.systemQa,
    area: 'Safe diagnostics',
    content: 'System QA contains read-only checks, CODEX_TEST guidance, access boundaries, and protection notes.',
    when: 'Use it for release checks or troubleshooting, not routine event-day flow.',
    action: 'Review health checks and confirm safe test boundaries before QA work.',
    example: 'Use CODEX_TEST for testing and keep CPB protected.',
    affects: 'System QA supports production safety without creating business records.',
  },
]

export const practiceMissions = [
  { id: 'select-codex-test', title: 'Confirm CODEX_TEST', writes: false },
  { id: 'open-create-event-cancel', title: 'Open Create Event and cancel', writes: false },
  { id: 'choose-category-no-save', title: 'Choose a category without saving', writes: false },
  { id: 'open-registration-filters', title: 'Open and clear registration filters', writes: false },
  { id: 'open-add-registration-cancel', title: 'Open Add Registration and cancel', writes: false },
  { id: 'inspect-payment-follow-up', title: 'Inspect payment follow-up', writes: false },
  { id: 'open-check-in-search', title: 'Open Check-In search', writes: false },
  { id: 'build-copy-message', title: 'Build and copy a sample message', writes: false },
]
