import { TUTORIAL_TARGETS } from './tutorialRegistry.js'

export const TUTORIAL_VERSION = 'tutorial-v3-specific-guidance'

export const E2E_TUTORIAL_UID = 'phase23p-e2e-organizer'

export const TARGET_UIDS = [
  'WcDU2jmbopdAgDlMMWvD3TkqqbC3',
  'WM2UOQtSeuOglCI5uMZQKrYYqP53',
  E2E_TUTORIAL_UID,
]

function lesson({
  id,
  title,
  routeId,
  pathname,
  targetId,
  area,
  what,
  why,
  doNow,
  next,
  example,
  showMe,
  letMeTry,
  prepare,
}) {
  return {
    id,
    title,
    routeId,
    pathname,
    targetId,
    area,
    what,
    why,
    doNow,
    next,
    example,
    showMe,
    letMeTry,
    prepare,
    writesBusinessData: false,
  }
}

export const guidedTutorialSteps = [
  lesson({
    id: 'working-event',
    title: 'Working Event',
    routeId: 'dashboard',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.workingEventSelector,
    area: 'Event scope',
    what: 'The Working Event strip shows which event all organizer pages are currently scoped to.',
    why: 'Use it before reviewing guests, payments, tickets, Operations, or reports so you do not mix event records.',
    doNow: 'Confirm the selected event name, date, and status in this strip.',
    next: 'Every page you open next loads records for this selected event only.',
    example: 'For a birthday brunch, select that brunch before adding guests or checking payment follow-up.',
    showMe: 'Highlight the event-change control without changing the event.',
    letMeTry: 'Verify the Working Event strip is visible and ready.',
  }),
  lesson({
    id: 'overview',
    title: 'Overview',
    routeId: 'dashboard',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.overviewPrimaryMetrics,
    area: 'Daily starting point',
    what: 'Overview is the first scan of event health: registrations, guests, money recorded, capacity, and attention items.',
    why: 'Use it to decide where to work next instead of opening every page manually.',
    doNow: 'Read the metric row and choose the highest-priority Needs Attention item.',
    next: 'The destination link sends you to the page that owns the follow-up.',
    example: 'If missing tickets appear, go to Tickets before event-day check-in starts.',
    showMe: 'Scroll the key numbers into view.',
    letMeTry: 'Verify the Overview metrics are visible.',
  }),
  lesson({
    id: 'create-event',
    title: 'Create Event',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventsCreateButton,
    area: 'Event setup',
    what: 'Create Event starts a new event workspace with its own guests, tickets, money, and reporting scope.',
    why: 'Use it when a new birthday, wedding, workshop, corporate event, private party, or showcase needs planning.',
    doNow: 'Select Create Event to begin planning a new event.',
    next: 'The event form opens. You can inspect it during the tutorial without saving.',
    example: 'A workshop gets its own date, venue, capacity, registration settings, and event-day plan.',
    showMe: 'Open the event form without saving.',
    letMeTry: 'Open the event form and confirm the Event Basics step appears.',
    prepare: { type: 'close-event-form' },
  }),
  lesson({
    id: 'event-basics',
    title: 'Event Basics',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventBasicsName,
    area: 'Event setup',
    what: 'Event Basics captures the event name, date, venue, location, status, and basic capacity context.',
    why: 'Use it to make the event recognizable across Overview, registrations, tickets, messages, and reports.',
    doNow: 'Focus the Event name field. Do not save anything during the tutorial.',
    next: 'The name you save later becomes the event identity shown throughout the app.',
    example: 'Use a clear name such as “Family Anniversary Dinner” instead of a short internal code.',
    showMe: 'Focus the Event name field.',
    letMeTry: 'Focus the Event name field yourself.',
    prepare: { type: 'open-event-form', formStep: 'basics' },
  }),
  lesson({
    id: 'event-category',
    title: 'Event Category',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventCategorySelector,
    area: 'Event setup',
    what: 'Event Category tells the app what kind of event you are planning.',
    why: 'Use it so the planning language and optional prompts match the event instead of assuming every event is the same.',
    doNow: 'Choose the category that most closely matches the event you are planning.',
    next: 'The category suggests suitable capabilities; it does not save until you create or update the event.',
    example: 'Birthday, Bridal Shower, Wedding, Workshop, Food Showcase, Cultural Experience, Corporate Event, Party, Private Event, and Other are normal choices.',
    showMe: 'Focus the category selector so you can open the list.',
    letMeTry: 'Open the category selector or change the temporary selection.',
    prepare: { type: 'open-event-form', formStep: 'basics' },
  }),
  lesson({
    id: 'event-capabilities',
    title: 'Optional Capabilities',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventCapabilities,
    area: 'Event setup',
    what: 'Optional Capabilities describe which planning prompts this event actually needs.',
    why: 'Use them to keep the workspace relevant and avoid showing unused specialty planning sections.',
    doNow: 'Turn on only the features this event needs.',
    next: 'The selected capabilities shape the planning workspace after the event is saved.',
    example: 'Ticketing, public registration, check-in, seating, vendors, sponsors, sessions, and transport are examples of event-specific needs.',
    showMe: 'Open the capability controls in the temporary form.',
    letMeTry: 'Toggle one temporary capability and leave the form unsaved.',
    prepare: { type: 'open-event-form', formStep: 'registration' },
  }),
  lesson({
    id: 'event-planning',
    title: 'Planning Tasks',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventPlanning,
    area: 'Planning workspace',
    what: 'Planning Tasks show setup work, readiness, financial planning, and next organizer actions for the selected event.',
    why: 'Use it before event day to keep venue, ticketing, communications, suppliers, and readiness work in one place.',
    doNow: 'Review the planning workspace and look for any readiness item that still needs action.',
    next: 'Planning progress feeds Overview and Reports without replacing the specialist pages.',
    example: 'Add a task to confirm venue access, then use Operations for actual supplier or sponsor records.',
    showMe: 'Close the unsaved form and show the planning workspace.',
    letMeTry: 'Confirm the planning workspace is visible.',
    prepare: { type: 'close-event-form' },
  }),
  lesson({
    id: 'registrations',
    title: 'Guests & Registrations',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsSummary,
    area: 'Guest records',
    what: 'Registrations are booking records. Guests are the people represented by those registrations.',
    why: 'Use this page to add, correct, filter, and review guest records for the selected event.',
    doNow: 'Compare registration count with guest count so group bookings remain clear.',
    next: 'These records feed Registration Payments, Tickets, Check-In, Message Builder, and Reports.',
    example: 'One registration can represent four guests attending together.',
    showMe: 'Scroll to the registration metrics.',
    letMeTry: 'Verify the registration and guest counts are visible.',
  }),
  lesson({
    id: 'add-registration',
    title: 'Add Registration',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsAddButton,
    area: 'Guest records',
    what: 'Add Registration opens the form for a new approved guest booking.',
    why: 'Use it when you have a real registration to enter or correct from an approved source.',
    doNow: 'Select Add registration to see where a new record starts.',
    next: 'The form can create guests, payment status, ticket readiness, and check-in records after saving.',
    example: 'Enter the buyer, contact details, persons attending, payment status, and ticket information only when confirmed.',
    showMe: 'Open the registration form without saving.',
    letMeTry: 'Open the registration form and cancel before saving.',
  }),
  lesson({
    id: 'registration-filters',
    title: 'Registration Filters',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationFilters,
    area: 'Guest records',
    what: 'Filters narrow the registration list by guest, contact, payment, ticket, review, and attendance state.',
    why: 'Use them before editing records or building follow-up messages.',
    doNow: 'Open or review the filters panel and choose a supported filter when needed.',
    next: 'The filtered list can guide payment review, tickets, check-in, or Message Builder work.',
    example: 'Filter unpaid registrations before creating a payment reminder message.',
    showMe: 'Scroll the filters panel into view.',
    letMeTry: 'Confirm the filters panel is visible.',
  }),
  lesson({
    id: 'payments',
    title: 'Registration Payments',
    routeId: 'payments',
    pathname: '/payments',
    targetId: TUTORIAL_TARGETS.paymentsSummary,
    area: 'Payment review',
    what: 'Registration Payments reviews charges, received amounts, balances, methods, evidence, and follow-up.',
    why: 'Use it for guest payment cleanup without mixing those records into the Operations Ledger.',
    doNow: 'Review expected income, payments received, and outstanding balance.',
    next: 'Payment follow-up rows help you decide who needs contact or internal cleanup.',
    example: 'A paid registration missing a method is cleanup work, not a guest reminder by itself.',
    showMe: 'Scroll the payment metrics into view.',
    letMeTry: 'Verify Registration Payments and Operations are shown as separate concepts.',
  }),
  lesson({
    id: 'tickets',
    title: 'Tickets',
    routeId: 'tickets',
    pathname: '/tickets',
    targetId: TUTORIAL_TARGETS.ticketsReadiness,
    area: 'Ticket preparation',
    what: 'Tickets prepares ticket codes and QR access for the selected event.',
    why: 'Use it before event day to find missing ticket codes and review readiness.',
    doNow: 'Review ticket status and assign or verify ticket codes using the existing workflow.',
    next: 'Ticket codes feed Check-In and scanner lookup.',
    example: 'A QR code carries the ticket code payload, not guest contact or payment data.',
    showMe: 'Scroll ticket readiness into view.',
    letMeTry: 'Verify the Tickets page is scoped to the Working Event.',
  }),
  lesson({
    id: 'check-in',
    title: 'Check-In',
    routeId: 'check-in',
    pathname: '/check-in',
    targetId: TUTORIAL_TARGETS.checkInSearch,
    area: 'Event day',
    what: 'Check-In finds guests by ticket, QR scan, name, buyer, contact, or attendee detail.',
    why: 'Use it at the door when a guest arrives and you need to confirm attendance.',
    doNow: 'Select the search field and enter a guest name or ticket code when checking in a real arrival.',
    next: 'A separate Check In action records attendance after the guest is matched.',
    example: 'Search the ticket code first, review the match, then check in only the arriving guest.',
    showMe: 'Focus the Check-In search field.',
    letMeTry: 'Focus the search field without checking anyone in.',
  }),
  lesson({
    id: 'operations',
    title: 'Operations Ledger',
    routeId: 'operations',
    pathname: '/operations',
    targetId: TUTORIAL_TARGETS.operationsLedgerSummary,
    area: 'Event-level ledger',
    what: 'Operations tracks event-level income, expenses, refunds, reimbursements, commitments, and adjustments.',
    why: 'Use it for sponsor income, supplier payments, vendor costs, expenses, and other event obligations.',
    doNow: 'Review the Operations summary before adding or editing ledger entries.',
    next: 'Operations remains separate from Registration Payments and appears separately in Reports.',
    example: 'Record a venue deposit here; do not duplicate a guest ticket payment as Operations income.',
    showMe: 'Scroll the Operations summary into view.',
    letMeTry: 'Verify the finance-boundary notice is visible.',
  }),
  lesson({
    id: 'partners',
    title: 'Partners, Suppliers, and Sponsors',
    routeId: 'operations',
    pathname: '/operations',
    targetId: TUTORIAL_TARGETS.partnersSponsors,
    area: 'Event relationships',
    what: 'This section keeps contact and commitment records for partners, suppliers, vendors, sponsors, venue contacts, and helpers.',
    why: 'Use it when outside people or organizations have responsibilities, contributions, or follow-up needs.',
    doNow: 'Open the partner commitments section and review its summary.',
    next: 'Confirmed money still belongs in the ledger only when it is actually received, paid, or committed.',
    example: 'Track a sponsor as requested, confirmed cash, or in-kind support without counting it as guest payment revenue.',
    showMe: 'Open the partner commitments section.',
    letMeTry: 'Verify the partner commitments panel is visible.',
    prepare: { type: 'open-details', selector: '[data-tour-container="partners-commitments"]' },
  }),
  lesson({
    id: 'communications',
    title: 'Message Builder',
    routeId: 'communications',
    pathname: '/communications',
    targetId: TUTORIAL_TARGETS.messageBuilder,
    area: 'Copy-only messaging',
    what: 'Message Builder helps create, personalize, preview, and copy event messages. It does not send automatically.',
    why: 'Use it when you need text for WhatsApp, email, SMS, or another external tool.',
    doNow: 'Choose a template or segment, preview the wording, then copy it for manual sending.',
    next: 'Copied messages can reference event, registration, ticket, and payment context without changing records.',
    example: 'Build an unpaid-balance reminder, copy it, and send it through your chosen communication channel.',
    showMe: 'Scroll the Message Builder workspace into view.',
    letMeTry: 'Verify the copy-only notice is visible.',
  }),
  lesson({
    id: 'reports',
    title: 'Reports',
    routeId: 'reports',
    pathname: '/event-review',
    targetId: TUTORIAL_TARGETS.reportsSummary,
    area: 'Read-only review',
    what: 'Reports summarizes follow-up, registration payments, Operations, attendance, and event status in a read-only view.',
    why: 'Use it for current review, closeout, or historical reference without creating or editing records.',
    doNow: 'Review Registration Payments and Operations as separate sections.',
    next: 'Use the source pages for corrections; Reports itself remains read-only.',
    example: 'Discuss final event results only after checking guest payment totals and Operations ledger totals separately.',
    showMe: 'Scroll the report summary into view.',
    letMeTry: 'Verify no save, reconcile, or delete action appears in Reports.',
  }),
  lesson({
    id: 'imports',
    title: 'Import Center',
    routeId: 'imports',
    pathname: '/imports',
    targetId: TUTORIAL_TARGETS.importCenterSource,
    area: 'Preview-first import',
    what: 'Import Center brings in CSV, pasted rows, and supported spreadsheets through a preview-first workflow.',
    why: 'Use it when registrations start in forms, sheets, workbooks, or another list.',
    doNow: 'Choose a source, map fields, preview rows, check duplicates, and import only approved records.',
    next: 'Rows create registration records only after explicit confirmation.',
    example: 'Paste a spreadsheet export, confirm the detected fields, then import only clean approved rows.',
    showMe: 'Scroll the import source options into view.',
    letMeTry: 'Verify the preview-first source area is visible.',
  }),
  lesson({
    id: 'settings',
    title: 'Settings',
    routeId: 'settings',
    pathname: '/settings',
    targetId: TUTORIAL_TARGETS.settingsTourReplay,
    area: 'Workspace configuration',
    what: 'Settings contains practical defaults, access summaries, scanner links, preferences, and tutorial replay.',
    why: 'Use it for configuration and account support rather than daily event work.',
    doNow: 'Find the tutorial replay and configuration areas.',
    next: 'Settings changes support the workspace but should not be used as an event report.',
    example: 'Replay this tutorial from Settings after the first run is complete.',
    showMe: 'Scroll the Settings workspace into view.',
    letMeTry: 'Verify the replay area is available.',
  }),
  lesson({
    id: 'system-qa',
    title: 'System QA and Help',
    routeId: 'system-qa',
    pathname: '/qa',
    targetId: TUTORIAL_TARGETS.systemQa,
    area: 'Safe diagnostics',
    what: 'System QA keeps diagnostics, safety checks, and test boundaries separate from daily organizer work.',
    why: 'Use it for release checks, troubleshooting, or supervised QA instead of normal event-day operations.',
    doNow: 'Review the safety guidance before any QA workflow.',
    next: 'Normal organizers can keep daily work in Overview, registrations, tickets, check-in, Operations, messages, and Reports.',
    example: 'A QA checklist can confirm route health without changing real event records.',
    showMe: 'Scroll the System QA workspace into view.',
    letMeTry: 'Verify System QA is visually separate from daily event tools.',
  }),
]

export const practiceMissions = [
  {
    id: 'choose-category-no-save',
    title: 'Mission: Choose an Event Category',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Event Category selector',
    action: 'Open the selector and choose Birthday in the temporary form.',
    successCondition: 'The temporary form state contains Birthday.',
    why: 'The category helps the app suggest suitable planning features. Nothing has been saved.',
    writes: false,
  },
  {
    id: 'open-create-event-cancel',
    title: 'Mission: Open Create Event and cancel',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Create Event',
    action: 'Open the form, inspect the first step, and cancel.',
    successCondition: 'The form opens and closes without saving.',
    why: 'This teaches where new event setup begins without creating a real event.',
    writes: false,
  },
  {
    id: 'open-registration-filters',
    title: 'Mission: Review Registration Filters',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Registration Filters',
    action: 'Open or review the filters panel and clear filters when finished.',
    successCondition: 'The filters panel is visible and no record is changed.',
    why: 'Filters help find follow-up work safely before editing data.',
    writes: false,
  },
  {
    id: 'open-add-registration-cancel',
    title: 'Mission: Open Add Registration and cancel',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Add Registration',
    action: 'Open the registration form and cancel before saving.',
    successCondition: 'The form closes without creating a record.',
    why: 'This shows the entry point for approved registrations without changing production data.',
    writes: false,
  },
  {
    id: 'build-copy-message',
    title: 'Mission: Preview a Message',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Message Builder',
    action: 'Open Message Builder and preview supported copy-only messaging.',
    successCondition: 'The copy-only message area is visible.',
    why: 'Messages are copied for manual sending; the app does not send automatically.',
    writes: false,
  },
]
