import { TUTORIAL_TARGETS } from './tutorialRegistry.js'

export const TUTORIAL_VERSION = 'tutorial-v4-organizer-modules'

export const E2E_TUTORIAL_UID = 'phase23p-e2e-organizer'

export const TARGET_UIDS = [
  'WcDU2jmbopdAgDlMMWvD3TkqqbC3',
  'WM2UOQtSeuOglCI5uMZQKrYYqP53',
  E2E_TUTORIAL_UID,
]

function lesson({
  id,
  title,
  routeId,
  pathname,
  targetId,
  area,
  what,
  why,
  doNow,
  next,
  example,
  showMe,
  letMeTry,
  prepare,
}) {
  return {
    id,
    title,
    routeId,
    pathname,
    targetId,
    area,
    what,
    why,
    doNow,
    next,
    example,
    showMe,
    letMeTry,
    prepare,
    writesBusinessData: false,
  }
}

export const guidedTutorialSteps = [
  lesson({
    id: 'working-event',
    title: 'Working Event',
    routeId: 'dashboard',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.workingEventSelector,
    area: 'Event scope',
    what: 'The Working Event strip shows which event all organizer pages are currently scoped to.',
    why: 'Use it before reviewing guests, payments, tickets, Operations, or reports so you do not mix event records.',
    doNow: 'Confirm the selected event name, date, and status in this strip.',
    next: 'Every page you open next loads records for this selected event only.',
    example: 'For a birthday brunch, select that brunch before adding guests or checking payment follow-up.',
    showMe: 'Highlight the event-change control without changing the event.',
    letMeTry: 'Verify the Working Event strip is visible and ready.',
  }),
  lesson({
    id: 'overview',
    title: 'Home',
    routeId: 'dashboard',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.overviewPrimaryMetrics,
    area: 'Daily starting point',
    what: 'Home is the first scan of event health: registrations, guests, money recorded, capacity, and attention items.',
    why: 'Use it to decide where to work next instead of opening every page manually.',
    doNow: 'Read the metric row and choose the highest-priority Needs Attention item.',
    next: 'The destination link sends you to the page that owns the follow-up.',
    example: 'If missing tickets appear, go to Tickets before event-day check-in starts.',
    showMe: 'Scroll the key numbers into view.',
    letMeTry: 'Verify the Home metrics are visible.',
  }),
  lesson({
    id: 'create-event',
    title: 'Create Event',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventsCreateButton,
    area: 'Event setup',
    what: 'Create Event starts a new event workspace with its own guests, tickets, money, and reporting scope.',
    why: 'Use it when a new birthday, wedding, workshop, corporate event, private party, or showcase needs planning.',
    doNow: 'Select Create Event to begin planning a new event.',
    next: 'The event form opens. You can inspect it during the tutorial without saving.',
    example: 'A workshop gets its own date, venue, capacity, registration settings, and event-day plan.',
    showMe: 'Open the event form without saving.',
    letMeTry: 'Open the event form and confirm the Event Basics step appears.',
    prepare: { type: 'close-event-form' },
  }),
  lesson({
    id: 'event-basics',
    title: 'Event Basics',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventBasicsName,
    area: 'Event setup',
    what: 'Event Basics captures the event name, date, venue, location, status, and basic capacity context.',
    why: 'Use it to make the event recognizable across Overview, registrations, tickets, messages, and reports.',
    doNow: 'Focus the Event name field. Do not save anything during the tutorial.',
    next: 'The name you save later becomes the event identity shown throughout the app.',
    example: 'Use a clear name such as “Family Anniversary Dinner” instead of a short internal code.',
    showMe: 'Focus the Event name field.',
    letMeTry: 'Focus the Event name field yourself.',
    prepare: { type: 'open-event-form', formStep: 'basics' },
  }),
  lesson({
    id: 'event-category',
    title: 'Event Category',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventCategorySelector,
    area: 'Event setup',
    what: 'Event Category tells the app what kind of event you are planning.',
    why: 'Use it so the planning language and optional prompts match the event instead of assuming every event is the same.',
    doNow: 'Choose the category that most closely matches the event you are planning.',
    next: 'The category suggests suitable capabilities; it does not save until you create or update the event.',
    example: 'Birthday, Bridal Shower, Wedding, Workshop, Food Showcase, Cultural Experience, Corporate Event, Party, Private Event, and Other are normal choices.',
    showMe: 'Focus the category selector so you can open the list.',
    letMeTry: 'Open the category selector or change the temporary selection.',
    prepare: { type: 'open-event-form', formStep: 'basics' },
  }),
  lesson({
    id: 'event-capabilities',
    title: 'Optional Capabilities',
    routeId: 'events',
    pathname: '/events',
    targetId: TUTORIAL_TARGETS.eventCapabilities,
    area: 'Event setup',
    what: 'Optional Capabilities describe which planning prompts this event actually needs.',
    why: 'Use them to keep the workspace relevant and avoid showing unused specialty planning sections.',
    doNow: 'Turn on only the features this event needs.',
    next: 'The selected capabilities shape the planning workspace after the event is saved.',
    example: 'Ticketing, public registration, check-in, seating, vendors, sponsors, sessions, and transport are examples of event-specific needs.',
    showMe: 'Open the capability controls in the temporary form.',
    letMeTry: 'Toggle one temporary capability and leave the form unsaved.',
    prepare: { type: 'open-event-form', formStep: 'registration' },
  }),
  lesson({
    id: 'tasks',
    title: 'Tasks & Deadlines',
    routeId: 'tasks',
    pathname: '/tasks',
    targetId: TUTORIAL_TARGETS.tasksWorkspace,
    area: 'Planning workflow',
    what: 'Tasks & Deadlines tracks event setup work, due dates, blockers, and follow-up for the selected Working Event.',
    why: 'Use it to keep planning work visible without turning registrations, payments, tickets, or Operations into a task system.',
    doNow: 'Review open, overdue, waiting, blocked, and completed task counts.',
    next: 'Tasks stay event-scoped and can point you back to the page that owns the actual work.',
    example: 'Track a deadline to confirm venue access, then record supplier payments in Operations only when money or obligations are involved.',
    showMe: 'Open the Tasks & Deadlines workspace.',
    letMeTry: 'Confirm the task summary and filters are visible.',
    prepare: { type: 'close-event-form' },
  }),
  lesson({
    id: 'registrations',
    title: 'Guests & Registrations',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsSummary,
    area: 'Guest records',
    what: 'Registrations are booking records. Guests are the people represented by those registrations.',
    why: 'Use this page to add, correct, filter, and review guest records for the selected event.',
    doNow: 'Compare registration count with guest count so group bookings remain clear.',
    next: 'These records feed Registration Payments, Tickets, Check-In, Message Builder, and Reports.',
    example: 'One registration can represent four guests attending together.',
    showMe: 'Scroll to the registration metrics.',
    letMeTry: 'Verify the registration and guest counts are visible.',
  }),
  lesson({
    id: 'add-registration',
    title: 'Add Registration',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsAddButton,
    area: 'Guest records',
    what: 'Add Registration opens the form for a new approved guest booking.',
    why: 'Use it when you have a real registration to enter or correct from an approved source.',
    doNow: 'Select Add registration to see where a new record starts.',
    next: 'The form can create guests, payment status, ticket readiness, and check-in records after saving.',
    example: 'Enter the buyer, contact details, persons attending, payment status, and ticket information only when confirmed.',
    showMe: 'Open the registration form without saving.',
    letMeTry: 'Open the registration form and cancel before saving.',
  }),
  lesson({
    id: 'registration-filters',
    title: 'Registration Filters',
    routeId: 'registrations',
    pathname: '/registrations',
    targetId: TUTORIAL_TARGETS.registrationsWorkspaceTabs,
    area: 'Guest records',
    what: 'The registration workspace keeps records first, with Daily Review and Bulk Actions separated into tabs.',
    why: 'Use them before editing records or building follow-up messages.',
    doNow: 'Keep Registration Records selected for normal work, or switch to Daily Review when checking issues.',
    next: 'The filtered list can guide payment review, tickets, check-in, or Message Builder work.',
    example: 'Filter unpaid registrations before creating a payment reminder message.',
    showMe: 'Scroll the registration workspace tabs into view.',
    letMeTry: 'Confirm the registration workspace tabs are visible.',
  }),
  lesson({
    id: 'payments',
    title: 'Registration Payments',
    routeId: 'payments',
    pathname: '/payments',
    targetId: TUTORIAL_TARGETS.paymentsSummary,
    area: 'Payment review',
    what: 'Registration Payments reviews charges, received amounts, balances, methods, evidence, and follow-up.',
    why: 'Use it for guest payment cleanup without mixing those records into the Operations Ledger.',
    doNow: 'Review expected income, payments received, and outstanding balance.',
    next: 'Payment follow-up rows help you decide who needs contact or internal cleanup.',
    example: 'A paid registration missing a method is cleanup work, not a guest reminder by itself.',
    showMe: 'Scroll the payment metrics into view.',
    letMeTry: 'Verify Registration Payments and Operations are shown as separate concepts.',
  }),
  lesson({
    id: 'tickets',
    title: 'Tickets',
    routeId: 'tickets',
    pathname: '/tickets',
    targetId: TUTORIAL_TARGETS.ticketsWorkspaceTabs,
    area: 'Ticket preparation',
    what: 'Tickets prepares ticket codes and QR access, with normal ticket records separated from assignment guidance and review tools.',
    why: 'Use it before event day to find missing ticket codes and review readiness.',
    doNow: 'Start with Ticket Records, then use Assignment & Delivery or Review & Tools only when that work is needed.',
    next: 'Ticket codes feed Check-In and scanner lookup.',
    example: 'A QR code carries the ticket code payload, not guest contact or payment data.',
    showMe: 'Scroll ticket workspace tabs into view.',
    letMeTry: 'Verify the Tickets page is scoped to the Working Event.',
  }),
  lesson({
    id: 'check-in',
    title: 'Check-In',
    routeId: 'check-in',
    pathname: '/check-in',
    targetId: TUTORIAL_TARGETS.checkInWorkspaceTabs,
    area: 'Event day',
    what: 'Check-In keeps the door workflow first and separates recent activity, issue review, and tools into tabs.',
    why: 'Use it at the door when a guest arrives and you need to confirm attendance.',
    doNow: 'Use Check In for live arrivals, then switch tabs only when reviewing activity, issues, or helper tools.',
    next: 'A separate Check In action records attendance after the guest is matched.',
    example: 'Search the ticket code first, review the match, then check in only the arriving guest.',
    showMe: 'Highlight the Check-In workspace tabs.',
    letMeTry: 'Verify the search field remains visible for live check-in.',
  }),
  lesson({
    id: 'operations',
    title: 'Operations Ledger',
    routeId: 'operations',
    pathname: '/operations',
    targetId: TUTORIAL_TARGETS.operationsLedgerSummary,
    area: 'Event-level ledger',
    what: 'Operations tracks event-level income, expenses, refunds, reimbursements, commitments, and adjustments.',
    why: 'Use it for sponsor income, supplier payments, vendor costs, expenses, and other event obligations.',
    doNow: 'Review the Operations summary before adding or editing ledger entries.',
    next: 'Operations remains separate from Registration Payments and appears separately in Reports.',
    example: 'Record a venue deposit here; do not duplicate a guest ticket payment as Operations income.',
    showMe: 'Scroll the Operations summary into view.',
    letMeTry: 'Verify the finance-boundary notice is visible.',
  }),
  lesson({
    id: 'commitments',
    title: 'Partner Commitments',
    routeId: 'operations',
    pathname: '/operations',
    targetId: TUTORIAL_TARGETS.partnersSponsors,
    area: 'Suppliers and partners',
    what: 'Partner Commitments tracks supplier, sponsor, vendor, venue, baker, helper, and in-kind promises separately from guest payments.',
    why: 'Use it when the obligation belongs to event operations instead of an individual registration.',
    doNow: 'Review the commitments panel and confirm whether the record is paid, partly paid, outstanding, or follow-up only.',
    next: 'Commitments can guide Operations ledger entries and follow-up tasks, but they do not rewrite registration payment records.',
    example: 'Track a baker invoice balance or sponsor promise here, then record actual money movement in the Operations ledger when confirmed.',
    showMe: 'Open the partner commitments workspace.',
    letMeTry: 'Verify the partner and supplier commitment boundary is visible.',
    prepare: { type: 'open-details', selector: '[data-tour-container="partners-commitments"]', operationsView: 'commitments' },
  }),
  lesson({
    id: 'run-of-show',
    title: 'Run of Show',
    routeId: 'run-of-show',
    pathname: '/run-of-show',
    targetId: TUTORIAL_TARGETS.runOfShowWorkspace,
    area: 'Event-day sequence',
    what: 'Run of Show is the private operational sequence for supplier arrivals, setup, programme activity, service, closing, and breakdown.',
    why: 'Use it when the team needs to know what happens now, what happens next, who is responsible, and which activities are delayed or complete.',
    doNow: 'Review the Now, Next, Upcoming, Delayed, and Recently Completed groups before changing any timeline item.',
    next: 'Status changes, expected or actual arrivals, dependencies, and linked records save only to the selected event timeline with audit evidence.',
    example: 'Add supplier arrival, doors opening, food service, speeches, closing, and breakdown in the order they should happen.',
    showMe: 'Open the Run of Show workspace and highlight the event-day timeline.',
    letMeTry: 'Verify the add-item action and timeline groups are visible without creating a record.',
  }),
  lesson({
    id: 'resources',
    title: 'Event Resources',
    routeId: 'resources',
    pathname: '/resources',
    targetId: TUTORIAL_TARGETS.resourcesWorkspace,
    area: 'Equipment and supplies',
    what: 'Resources tracks event-specific equipment, supplies, printed material, pickup, return, packing, suppliers, and shortages.',
    why: 'Use it to confirm what is needed, how much is confirmed, who is supplying it, where it belongs, and whether it has reached the venue.',
    doNow: 'Review quantity needed, quantity confirmed, shortage, lifecycle status, supplier, pickup, return, and packing details.',
    next: 'Links to Run of Show, Tasks, Documents, Operations, or Commitments remain relationships only and do not change amounts, status, or quantities on linked records.',
    example: 'Track whether 20 chairs are needed, 16 are confirmed, who is supplying them, when they must be collected, and whether they are on site.',
    showMe: 'Open the Resources workspace and highlight the resource summary.',
    letMeTry: 'Verify shortage and lifecycle controls are visible without changing a resource.',
  }),
  lesson({
    id: 'documents',
    title: 'Documents',
    routeId: 'documents',
    pathname: '/documents',
    targetId: TUTORIAL_TARGETS.documentsWorkspace,
    area: 'Reference records',
    what: 'Documents stores event-scoped document references such as contracts, receipts, agreements, quotes, menus, permits, and checklists.',
    why: 'Use it to track what exists, what is missing, and where the real file lives without uploading private files into the app.',
    doNow: 'Review required, missing, expiring, current, and linked document references for the selected Working Event.',
    next: 'Document links provide context for Tasks, Operations, Run of Show, Resources, and Contacts without changing those records automatically.',
    example: 'Add a venue agreement reference with its external Drive link, expiry date, and linked supplier contact.',
    showMe: 'Open the Documents workspace.',
    letMeTry: 'Verify the document-reference boundary and status filters are visible.',
  }),
  lesson({
    id: 'contacts',
    title: 'Contacts',
    routeId: 'contacts',
    pathname: '/contacts',
    targetId: TUTORIAL_TARGETS.contactsWorkspace,
    area: 'Reusable directory',
    what: 'Contacts stores reusable people such as venue managers, suppliers, sponsors, volunteers, speakers, school contacts, and helpers.',
    why: 'Use it to keep planning contact details in one directory without turning those people into app users.',
    doNow: 'Review the People view and confirm which contacts are linked to the selected Working Event.',
    next: 'Contacts can support messages and follow-up tasks, but they do not grant access or assign staff roles.',
    example: 'Keep a venue manager contact once, then link that person to any event where they are relevant.',
    showMe: 'Open the People tab in Contacts & Organizations.',
    letMeTry: 'Verify the contacts access boundary is visible.',
    prepare: { type: 'select-tab', panelId: 'people-panel' },
  }),
  lesson({
    id: 'organizations',
    title: 'Organizations',
    routeId: 'contacts',
    pathname: '/contacts',
    targetId: TUTORIAL_TARGETS.organizationsWorkspace,
    area: 'Reusable directory',
    what: 'Organizations stores reusable venues, suppliers, sponsors, schools, vendors, and partner businesses.',
    why: 'Use it when the relationship is with a business or group rather than only a named person.',
    doNow: 'Review the Organizations tab and check primary contact, category, status, and planning notes.',
    next: 'Organizations can be linked to event relationships, Operations, Documents, and planning records as context.',
    example: 'Store a venue once with its primary contact and reuse it across multiple events.',
    showMe: 'Open the Organizations tab.',
    letMeTry: 'Verify organization records are separate from people records.',
    prepare: { type: 'select-tab', panelId: 'organizations-panel' },
  }),
  lesson({
    id: 'event-relationships',
    title: 'Event Relationships',
    routeId: 'contacts',
    pathname: '/contacts',
    targetId: TUTORIAL_TARGETS.eventRelationshipsWorkspace,
    area: 'Event context',
    what: 'Event Relationships connect reusable contacts and organizations to the selected Working Event with event-specific roles.',
    why: 'Use them when the same contact has different responsibilities from event to event.',
    doNow: 'Review relationship type, event role, status, and primary-for-event flags.',
    next: 'A relationship adds event context only and does not copy records, grant access, or update money, tasks, documents, or timeline entries.',
    example: 'Mark a supplier as primary decorator for one event while keeping the supplier contact reusable for another event.',
    showMe: 'Open the Event Relationships tab.',
    letMeTry: 'Verify the event-relationship boundary is visible.',
    prepare: { type: 'select-tab', panelId: 'relationships-panel' },
  }),
  lesson({
    id: 'event-readiness',
    title: 'Event Readiness',
    routeId: 'dashboardReadiness',
    pathname: '/dashboard',
    targetId: TUTORIAL_TARGETS.eventReadinessSummary,
    area: 'Operational readiness',
    what: 'Event Readiness turns visible conditions into Ready, Needs Attention, or At Risk reasons the organizer can inspect.',
    why: 'Use it to understand why an event needs follow-up instead of relying on an unexplained percentage or hidden score.',
    doNow: 'Read each Needs Attention reason and use the destination link for the page that owns the correction.',
    next: 'Readiness recalculates when underlying records change, such as resolving a shortage, completing packing, or moving a delayed item forward.',
    example: 'A shortage of chairs, a delayed supplier, or an unresolved critical timeline dependency may move the event to Needs Attention or At Risk.',
    showMe: 'Highlight the Needs Attention and readiness explanation on Home.',
    letMeTry: 'Verify the reasons are visible and point to supported destinations.',
  }),
  lesson({
    id: 'reconciliation',
    title: 'Review & Reconcile Records',
    routeId: 'reconciliation',
    pathname: '/payments/reconciliation',
    targetId: TUTORIAL_TARGETS.reconciliationWorkspace,
    area: 'Payment evidence review',
    what: 'Review & Reconcile Records compares an approved payment workbook with the selected event payment records without saving changes.',
    why: 'Use it to distinguish payment balance from evidence discrepancy before making audited corrections in normal workflows.',
    doNow: 'Confirm the page is dry-run only and scoped to the selected Working Event.',
    next: 'Any correction must happen through the normal audited registration-payment workflow.',
    example: 'A missing workbook reference can require manual evidence review without automatically marking a guest unpaid.',
    showMe: 'Open the read-only reconciliation workspace.',
    letMeTry: 'Verify the preview-only guardrail is visible.',
  }),
  lesson({
    id: 'communications',
    title: 'Message Builder',
    routeId: 'communications',
    pathname: '/communications',
    targetId: TUTORIAL_TARGETS.messageBuilder,
    area: 'Copy-only messaging',
    what: 'Message Builder helps create, personalize, preview, and copy event messages. It does not send automatically.',
    why: 'Use it when you need text for WhatsApp, email, SMS, or another external tool.',
    doNow: 'Choose a template or segment, preview the wording, then copy it for manual sending.',
    next: 'Copied messages can reference event, registration, ticket, and payment context without changing records.',
    example: 'Build an unpaid-balance reminder, copy it, and send it through your chosen communication channel.',
    showMe: 'Scroll the Message Builder workspace into view.',
    letMeTry: 'Verify the copy-only notice is visible.',
  }),
  lesson({
    id: 'reports',
    title: 'Reports',
    routeId: 'reports',
    pathname: '/event-review',
    targetId: TUTORIAL_TARGETS.reportsSummary,
    area: 'Read-only review',
    what: 'Reports summarizes follow-up, registration payments, Operations, attendance, and event status in a read-only view.',
    why: 'Use it for current review, closeout, or historical reference without creating or editing records.',
    doNow: 'Review Registration Payments and Operations as separate sections.',
    next: 'Use the source pages for corrections; Reports itself remains read-only.',
    example: 'Discuss final event results only after checking guest payment totals and Operations ledger totals separately.',
    showMe: 'Scroll the report summary into view.',
    letMeTry: 'Verify no save, reconcile, or delete action appears in Reports.',
  }),
  lesson({
    id: 'imports',
    title: 'Import Center',
    routeId: 'imports',
    pathname: '/imports',
    targetId: TUTORIAL_TARGETS.importCenterSource,
    area: 'Preview-first import',
    what: 'Import Center brings in CSV, pasted rows, and supported spreadsheets through a preview-first workflow.',
    why: 'Use it when registrations start in forms, sheets, workbooks, or another list.',
    doNow: 'Choose a source, map fields, preview rows, check duplicates, and import only approved records.',
    next: 'Rows create registration records only after explicit confirmation.',
    example: 'Paste a spreadsheet export, confirm the detected fields, then import only clean approved rows.',
    showMe: 'Scroll the import source options into view.',
    letMeTry: 'Verify the preview-first source area is visible.',
  }),
  lesson({
    id: 'response-inbox',
    title: 'Response Inbox',
    routeId: 'imports',
    pathname: '/imports',
    targetId: TUTORIAL_TARGETS.responseInboxWorkspace,
    area: 'Form response review',
    what: 'Response Inbox reviews pasted Google Forms responses before any approved rows continue to import mapping.',
    why: 'Use it to separate new responses, duplicates, missing information, wait-list decisions, approvals, and history before creating records.',
    doNow: 'Review the inbox statuses and approve only responses that are safe to continue into mapping.',
    next: 'Approved guest-registration responses can continue to mapping; other response types remain review records until a supported conversion exists.',
    example: 'Approve a complete guest-registration response and hold a duplicate response for manual review.',
    showMe: 'Open the Response Inbox tab.',
    letMeTry: 'Verify no response becomes a registration automatically.',
    prepare: { type: 'select-tab', panelId: 'response-inbox-panel' },
  }),
  lesson({
    id: 'import-templates',
    title: 'Import Templates',
    routeId: 'imports',
    pathname: '/imports',
    targetId: TUTORIAL_TARGETS.importTemplatesWorkspace,
    area: 'Import preparation',
    what: 'Import Templates and help explain the supported columns and source expectations before you load registration rows.',
    why: 'Use them to prepare cleaner exports and reduce duplicate review, blocked rows, and manual corrections.',
    doNow: 'Review the template guidance before importing from a new form or spreadsheet.',
    next: 'Prepared source files move through the same preview, mapping, validation, review, confirmation, and result workflow.',
    example: 'Use a template header set for names, contact details, persons attending, ticket status, and payment status.',
    showMe: 'Open the Templates and Help tab.',
    letMeTry: 'Verify the import guidance is separate from the active import workflow.',
    prepare: { type: 'select-tab', panelId: 'templates-panel' },
  }),
  lesson({
    id: 'settings',
    title: 'Settings',
    routeId: 'settings',
    pathname: '/settings',
    targetId: TUTORIAL_TARGETS.settingsTourReplay,
    area: 'Workspace configuration',
    what: 'Settings contains practical defaults, access summaries, scanner links, preferences, and tutorial replay.',
    why: 'Use it for configuration and account support rather than daily event work.',
    doNow: 'Find the tutorial replay and configuration areas.',
    next: 'Settings changes support the workspace but should not be used as an event report.',
    example: 'Replay this tutorial from Settings after the first run is complete.',
    showMe: 'Scroll the Settings workspace into view.',
    letMeTry: 'Verify the replay area is available.',
  }),
  lesson({
    id: 'system-qa',
    title: 'System QA and Help',
    routeId: 'system-qa',
    pathname: '/qa',
    targetId: TUTORIAL_TARGETS.systemQa,
    area: 'Safe diagnostics',
    what: 'System QA keeps diagnostics, safety checks, and test boundaries separate from daily organizer work.',
    why: 'Use it for release checks, troubleshooting, or supervised QA instead of normal event-day operations.',
    doNow: 'Review the safety guidance before any QA workflow.',
    next: 'Normal organizers can keep daily work in Overview, registrations, tickets, check-in, Operations, messages, and Reports.',
    example: 'A QA checklist can confirm route health without changing real event records.',
    showMe: 'Scroll the System QA workspace into view.',
    letMeTry: 'Verify System QA is visually separate from daily event tools.',
  }),
]

export const practiceMissions = [
  {
    id: 'choose-category-no-save',
    title: 'Mission: Choose an Event Category',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Event Category selector',
    action: 'Open the selector and choose Birthday in the temporary form.',
    successCondition: 'The temporary form state contains Birthday.',
    why: 'The category helps the app suggest suitable planning features. Nothing has been saved.',
    writes: false,
  },
  {
    id: 'open-create-event-cancel',
    title: 'Mission: Open Create Event and cancel',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Create Event',
    action: 'Open the form, inspect the first step, and cancel.',
    successCondition: 'The form opens and closes without saving.',
    why: 'This teaches where new event setup begins without creating a real event.',
    writes: false,
  },
  {
    id: 'open-registration-filters',
    title: 'Mission: Review Registration Filters',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Registration Filters',
    action: 'Open or review the filters panel and clear filters when finished.',
    successCondition: 'The filters panel is visible and no record is changed.',
    why: 'Filters help find follow-up work safely before editing data.',
    writes: false,
  },
  {
    id: 'open-add-registration-cancel',
    title: 'Mission: Open Add Registration and cancel',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Add Registration',
    action: 'Open the registration form and cancel before saving.',
    successCondition: 'The form closes without creating a record.',
    why: 'This shows the entry point for approved registrations without changing production data.',
    writes: false,
  },
  {
    id: 'build-copy-message',
    title: 'Mission: Preview a Message',
    banner: 'Practice Mode — Nothing here affects your real events.',
    target: 'Message Builder',
    action: 'Open Message Builder and preview supported copy-only messaging.',
    successCondition: 'The copy-only message area is visible.',
    why: 'Messages are copied for manual sending; the app does not send automatically.',
    writes: false,
  },
]
