export const pageGuidance = {
  '/dashboard': {
    label: 'Plan',
    purpose: 'Start on Home to understand the selected event, attention items, guest totals, registration money, and next actions.',
    primaryAction: 'Review Needs Attention',
    boundary: 'Home summarizes work; use the linked pages to make changes.',
  },
  '/events': {
    label: 'Plan',
    purpose: 'Create, select, and update events. Completed real events remain editable by approved organizers.',
    primaryAction: 'Create or edit an event',
    boundary: 'Test events are hidden until Show Test Events is enabled.',
  },
  '/tasks': {
    label: 'Plan',
    purpose: 'Track event-scoped tasks, owners, blockers, waiting items, and follow-up dates.',
    primaryAction: 'Add Task',
    boundary: 'Completing a task does not automatically update resources, documents, money, or attendance.',
  },
  '/registrations': {
    label: 'Guests & attendance',
    purpose: 'Manage registration records, guest counts, contact details, payment fields, and ticket readiness.',
    primaryAction: 'Add Registration',
    boundary: 'A registration may represent more than one guest; Operations remains a separate event-level ledger.',
  },
  '/payments': {
    label: 'Money & follow-up',
    purpose: 'Review registration charges, recorded payments, balances, evidence, and follow-up states.',
    primaryAction: 'Review payment follow-up',
    boundary: 'Registration payments are not merged into Operations Ledger totals automatically.',
  },
  '/payments/reconciliation': {
    label: 'Money & follow-up',
    purpose: 'Review and reconcile records by comparing workbook payment evidence against the selected Working Event before any approved correction workflow.',
    primaryAction: 'Compare records',
    boundary: 'This preview does not write records by itself.',
  },
  '/tickets': {
    label: 'Guests & attendance',
    purpose: 'Assign ticket codes, review ticket status, and prepare QR access for the selected event.',
    primaryAction: 'Assign or review tickets',
    boundary: 'QR payload remains GSV:TICKET:{ticketCode}.',
  },
  '/check-in': {
    label: 'Guests & attendance',
    purpose: 'Check in assigned tickets and review attendance for the selected event.',
    primaryAction: 'Search or scan ticket',
    boundary: 'Guest totals are derived from personsAttending; normal scanner undo and check-out stay disabled.',
  },
  '/operations': {
    label: 'Money & follow-up',
    purpose: 'Track sponsor income, vendor payments, supplier costs, reimbursements, refunds, and adjustments.',
    primaryAction: 'Add Operations entry',
    boundary: 'Do not enter every registration payment here; those belong in Registration Payments.',
  },
  '/run-of-show': {
    label: 'Event day',
    purpose: 'Plan timing, arrivals, responsibilities, dependencies, and Now/Next event-day status.',
    primaryAction: 'Add Run of Show item',
    boundary: 'This is an internal operations schedule, not a public guest agenda.',
  },
  '/resources': {
    label: 'Event day',
    purpose: 'Track what must be confirmed, packed, brought on site, collected, and returned.',
    primaryAction: 'Add Resource',
    boundary: 'Resource updates do not change Operations, registration payments, or task status automatically.',
  },
  '/documents': {
    label: 'Plan',
    purpose: 'Track event document links, evidence references, required paperwork, due dates, and status.',
    primaryAction: 'Add Document',
    boundary: 'This records references only; it does not upload private files.',
  },
  '/contacts': {
    label: 'Plan',
    purpose: 'Manage reusable contacts, organizations, and event relationships for planning coordination.',
    primaryAction: 'Add Contact',
    boundary: 'Linking a person or organization does not grant app access.',
  },
  '/communications': {
    label: 'Tools',
    purpose: 'Choose recipients, select a template, preview merge fields, and copy event messages for use outside the app.',
    primaryAction: 'Create and copy message',
    boundary: 'Messages are not sent automatically and no live AI or delivery tracking is enabled.',
  },
  '/event-review': {
    label: 'Money & follow-up',
    purpose: 'Review read-only follow-up, registration payments, Operations summary, and event summary.',
    primaryAction: 'Review report',
    boundary: 'Reports explain current data; they do not create, reconcile, save, or delete records.',
  },
  '/imports': {
    label: 'Tools',
    purpose: 'Choose an import source, review response inbox rows when needed, map fields, validate, and preview before saving.',
    primaryAction: 'Choose import source',
    boundary: 'Use CODEX_DEMO for synthetic import rehearsal before touching a real event.',
  },
  '/settings': {
    label: 'System',
    purpose: 'Review practical app defaults and configuration that already exists.',
    primaryAction: 'Review settings',
    boundary: 'Technical diagnostics and release checks belong in System QA.',
  },
  '/qa': {
    label: 'System',
    purpose: 'Check diagnostics, protected-owner access, fixture identity, and production-safety guardrails.',
    primaryAction: 'Run QA Checks',
    boundary: 'Use CODEX_DEMO for synthetic QA; do not use real events for test writes.',
  },
}
