// This manifest is intentionally compact: it maps the mobile experience to the
// authoritative web route manifest without copying web rendering concerns.
export const MOBILE_PARITY_MANIFEST = Object.freeze([
  { featureId: 'overview', webRoute: '/dashboard', nativeRoute: '/home', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['viewOverview'], requiresWorkingEvent: true, readModel: 'dashboardOverviewModel', writeService: null, offlineBehavior: 'read-only summary; writes require connection', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'event-selection', webRoute: '/events', nativeRoute: '/events', nativeAvailability: 'NATIVE FULL', requiredCapabilities: ['viewOverview'], requiresWorkingEvent: false, readModel: 'assignedEvents', writeService: null, offlineBehavior: 'cached selection only', scannerRelevant: true, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'registrations', webRoute: '/registrations', nativeRoute: '/lookup', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['viewOverview'], requiresWorkingEvent: true, readModel: 'registrationListModel', writeService: 'registrations', offlineBehavior: 'bounded cached reads; no false write success', scannerRelevant: true, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'tickets', webRoute: '/tickets', nativeRoute: '/lookup', nativeAvailability: 'NATIVE READ ONLY', requiredCapabilities: ['viewOverview'], requiresWorkingEvent: true, readModel: 'ticketLookup', writeService: null, offlineBehavior: 'lookup requires available data', scannerRelevant: true, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'payments', webRoute: '/payments', nativeRoute: '/reports', nativeAvailability: 'NATIVE READ ONLY', requiredCapabilities: ['manageRegistrationPayments'], requiresWorkingEvent: true, readModel: 'paymentReconciliationModel', writeService: null, offlineBehavior: 'summary only', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'scanner', webRoute: '/check-in', nativeRoute: '/scanner', nativeAvailability: 'NATIVE FULL', requiredCapabilities: ['performOwnerCheckIn'], requiresWorkingEvent: true, readModel: 'checkInQueueModel', writeService: 'checkin', offlineBehavior: 'offline success prohibited; retry after reconnect', scannerRelevant: true, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'tasks', webRoute: '/tasks', nativeRoute: '/tasks', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['manageTasks'], requiresWorkingEvent: true, readModel: 'taskList', writeService: 'tasks', offlineBehavior: 'explicit retry on failed write', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'operations', webRoute: '/operations', nativeRoute: '/notes', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['manageOperations'], requiresWorkingEvent: true, readModel: 'operationsSummaryModel', writeService: null, offlineBehavior: 'read-only when offline', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'run-of-show', webRoute: '/run-of-show', nativeRoute: null, nativeAvailability: 'WEB DEEP LINK', requiredCapabilities: ['manageRunOfShow'], requiresWorkingEvent: true, readModel: 'runOfShow', writeService: null, offlineBehavior: 'web required', scannerRelevant: false, ownerRelevant: true, status: 'PLANNED' },
  { featureId: 'contacts', webRoute: '/contacts', nativeRoute: '/contacts', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['manageContactsAndOrganizations'], requiresWorkingEvent: true, readModel: 'contacts', writeService: 'contacts', offlineBehavior: 'bounded reads', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'resources', webRoute: '/resources', nativeRoute: null, nativeAvailability: 'WEB DEEP LINK', requiredCapabilities: ['manageResources'], requiresWorkingEvent: true, readModel: 'resources', writeService: null, offlineBehavior: 'web required', scannerRelevant: false, ownerRelevant: true, status: 'PLANNED' },
  { featureId: 'documents', webRoute: '/documents', nativeRoute: '/notes', nativeAvailability: 'NATIVE READ ONLY', requiredCapabilities: ['manageDocuments'], requiresWorkingEvent: true, readModel: 'documents', writeService: null, offlineBehavior: 'bounded reads', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'reports', webRoute: '/event-review', nativeRoute: '/reports', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['viewReports'], requiresWorkingEvent: true, readModel: 'reportSummary', writeService: null, offlineBehavior: 'summary only', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
  { featureId: 'payment-reconciliation', webRoute: '/payments/reconciliation', nativeRoute: null, nativeAvailability: 'WEB DEEP LINK', requiredCapabilities: ['manageRegistrationPayments'], requiresWorkingEvent: true, readModel: 'paymentReconciliationModel', writeService: null, offlineBehavior: 'web required', scannerRelevant: false, ownerRelevant: true, status: 'PLANNED' },
  { featureId: 'imports', webRoute: '/imports', nativeRoute: null, nativeAvailability: 'WEB ONLY BY DESIGN', requiredCapabilities: ['useImportCenter'], requiresWorkingEvent: true, readModel: 'importPreviewModel', writeService: 'importService', offlineBehavior: 'web required', scannerRelevant: false, ownerRelevant: true, status: 'WEB ONLY BY DESIGN' },
  { featureId: 'communications', webRoute: '/communications', nativeRoute: null, nativeAvailability: 'WEB ONLY BY DESIGN', requiredCapabilities: ['useMessageBuilder'], requiresWorkingEvent: true, readModel: null, writeService: null, offlineBehavior: 'web required', scannerRelevant: false, ownerRelevant: true, status: 'WEB ONLY BY DESIGN' },
  { featureId: 'system-qa', webRoute: '/qa', nativeRoute: '/settings', nativeAvailability: 'WEB DEEP LINK', requiredCapabilities: ['useSystemQa'], requiresWorkingEvent: false, readModel: 'runtimeHealth', writeService: null, offlineBehavior: 'web required', scannerRelevant: false, ownerRelevant: true, status: 'PLANNED' },
  { featureId: 'settings', webRoute: '/settings', nativeRoute: '/settings', nativeAvailability: 'NATIVE COMPACT', requiredCapabilities: ['useSettings'], requiresWorkingEvent: false, readModel: 'accountStatus', writeService: null, offlineBehavior: 'local session only', scannerRelevant: false, ownerRelevant: true, status: 'PARITY PARTIAL' },
])

export function getMobileParity(featureId) {
  return MOBILE_PARITY_MANIFEST.find((entry) => entry.featureId === featureId) || null
}
