import { useEffect, useState } from 'react'
import { Redirect, useRouter } from 'expo-router'
import { Text, View } from 'react-native'
import { Banner, EmptyState, Field, LoadingView, Pill, PrimaryButton, Screen, Section, SecondaryButton } from '@/components/ui'
import { colors, spacing, typography } from '@/design/tokens'
import { useAuth } from '@/providers/useAuth'
import { useActiveEvent } from '@/providers/useActiveEvent'
import { loadRegistrationPage, searchRegistrations } from '@/services/registrations'
import { createNativeRegistration, updateNativeRegistration } from '@/services/registrationMutations'

function nameOf(registration) { return registration.fullName || registration.buyerName || 'Unnamed guest' }

export default function RegistrationsManagementScreen() {
  const router = useRouter(); const { authInitialized, isAuthorized, access, user } = useAuth(); const { activeEvent, ready } = useActiveEvent()
  const [records, setRecords] = useState([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false)
  useEffect(() => { let cancelled = false; if (!activeEvent?.eventId) return undefined; Promise.resolve().then(() => { if (!cancelled) setLoading(true); return loadRegistrationPage(activeEvent.eventId, { pageSize: 50 }) }).then((page) => { if (!cancelled) setRecords(page.registrations) }).catch((nextError) => { if (!cancelled) setError(nextError?.message || 'Registrations could not be loaded.') }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [activeEvent?.eventId])
  if (!authInitialized || !ready) return <LoadingView label="Loading registrations" />
  if (!isAuthorized) return <Redirect href="/sign-in" />
  if (!activeEvent?.eventId) return <Redirect href="/events" />
  const canManage = Boolean(access?.protectedOwner || access?.isAdmin || access?.role === 'owner' || access?.role === 'admin')
  if (editing) return <RegistrationForm initial={editing === 'new' ? null : editing} saving={saving} onCancel={() => setEditing(null)} onSave={async (values) => { setSaving(true); setError(''); try { if (editing === 'new') await createNativeRegistration(values, activeEvent.eventId, user); else await updateNativeRegistration(editing, values, user); setEditing(null); const page = await loadRegistrationPage(activeEvent.eventId, { pageSize: 50 }); setRecords(page.registrations) } catch (nextError) { setError(nextError?.message || 'Registration could not be saved.') } finally { setSaving(false) } }} />
  const filtered = query.trim() ? searchRegistrations(records, query, 50) : records
  return <Screen scroll back><Section eyebrow="Registration management" title="Registrations" description="Review bounded records for the working event. Guests remains optimized for fast event-day lookup.">
    {error ? <Banner tone="danger">{error}</Banner> : null}<Field label="Search records" value={query} onChangeText={setQuery} placeholder="Name, email, phone, or ticket" autoCapitalize="none" />{canManage ? <PrimaryButton label="Create registration" onPress={() => setEditing('new')} /> : null}
    {loading ? <EmptyState title="Loading registrations" description="Preparing the working event records." /> : filtered.length === 0 ? <EmptyState title={query ? 'No matching registrations' : 'No registrations yet'} description="No records were found for this event." /> : <View style={{ gap: spacing.sm }}>{filtered.map((registration) => <View key={registration.registrationId} style={{ padding: spacing.md, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border, gap: spacing.sm }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}><View style={{ flex: 1 }}><Text style={{ ...typography.section, color: colors.text }}>{nameOf(registration)}</Text><Text style={{ ...typography.caption, color: colors.textMuted }}>{registration.email || registration.phone || 'No contact recorded'}</Text></View><Pill tone={registration.checkedIn ? 'warning' : 'success'}>{registration.checkedIn ? 'Checked in' : 'Registered'}</Pill></View><Text style={{ ...typography.caption, color: colors.textSubtle }}>Ticket: {registration.ticketCode || 'Not assigned'} · Payment: {registration.paymentStatus || 'Unknown'}</Text>{canManage ? <SecondaryButton label="Edit registration" onPress={() => setEditing(registration)} /> : null}<SecondaryButton label="View registration" onPress={() => router.push(`/guest/${registration.registrationId}`)} /></View>)}</View>}
  </Section></Screen>
}

function RegistrationForm({ initial, saving, onCancel, onSave }) {
  const [values, setValues] = useState({ fullName: initial?.fullName || '', buyerName: initial?.buyerName || '', attendeeNames: initial?.attendeeNames || [], email: initial?.email || '', phone: initial?.phone || '', groupName: initial?.groupName || '', personsAttending: String(initial?.personsAttending || 1), paymentStatus: initial?.paymentStatus || 'unknown', priceTier: initial?.priceTier || '', ticketPrice: String(initial?.ticketPrice || ''), amountDue: String(initial?.amountDue || ''), amountPaid: String(initial?.amountPaid || ''), balanceDue: String(initial?.balanceDue || ''), paymentMethod: initial?.paymentMethod || 'unknown', paymentReference: initial?.paymentReference || '', notes: initial?.notes || '' })
  const set = (key) => (value) => setValues((current) => ({ ...current, [key]: value }))
  return <Screen scroll back><Section eyebrow="Registration" title={initial ? 'Edit registration' : 'New registration'} description="Required and finance fields follow the Event Hub registration contract."><Field label="Full name" value={values.fullName} onChangeText={set('fullName')} placeholder="Full name" /><Field label="Buyer / contact" value={values.buyerName} onChangeText={set('buyerName')} placeholder="Buyer name" /><Field label="Attendee names" value={Array.isArray(values.attendeeNames) ? values.attendeeNames.join('\n') : values.attendeeNames} onChangeText={set('attendeeNames')} placeholder="One name per line" /><Field label="Email" value={values.email} onChangeText={set('email')} placeholder="name@example.com" autoCapitalize="none" /><Field label="Phone" value={values.phone} onChangeText={set('phone')} placeholder="Phone" /><Field label="Persons attending" value={values.personsAttending} onChangeText={set('personsAttending')} placeholder="1" autoCapitalize="none" /><Field label="Payment status" value={values.paymentStatus} onChangeText={set('paymentStatus')} placeholder="paid, pending, complimentary, door" autoCapitalize="none" /><Field label="Payment reference" value={values.paymentReference} onChangeText={set('paymentReference')} placeholder="Optional reference" /><Field label="Notes" value={values.notes} onChangeText={set('notes')} placeholder="Optional notes" /><PrimaryButton label={saving ? 'Saving…' : 'Save registration'} onPress={() => onSave(values)} disabled={saving} /><SecondaryButton label="Cancel" onPress={onCancel} disabled={saving} /></Section></Screen>
}
