export const walkthroughSteps = [
  {
    id: 'working-event',
    title: 'Working Event',
    route: '/dashboard',
    targetId: 'working-event-selector',
    content: 'Everything in the organizer app is scoped to one selected event.',
    when: 'Use this whenever you need to switch from one event to another or confirm what data you are viewing.',
    example: 'Before editing registrations, confirm CODEX_TEST or the correct live event is selected here.',
  },
  {
    id: 'overview',
    title: 'Overview',
    route: '/dashboard',
    targetId: 'overview-summary',
    content: 'Overview is the daily starting point for current-event metrics, attention items, and next actions.',
    when: 'Open it first when you want to know what needs work today.',
    example: 'Check registration count, guest count, payments received, and capacity before deciding what to do next.',
  },
  {
    id: 'create-event',
    title: 'Creating an Event',
    route: '/events',
    targetId: 'create-event-action',
    content: 'Create each gathering once, then keep planning information attached to that event.',
    when: 'Use this when a new birthday, wedding, workshop, tasting, or private event needs its own workspace.',
    example: 'Plan a bridal shower with its own date, venue, capacity, registration rules, and Operations records.',
  },
  {
    id: 'event-capabilities',
    title: 'Event Category and Capabilities',
    route: '/events',
    targetId: 'event-planning-workspace',
    content: 'Event type suggests useful defaults, and capabilities describe which optional planning prompts matter.',
    when: 'Review capabilities when an event is not a standard ticketed food event.',
    example: 'A workshop may need sessions and certificates; a wedding may need seating, bridal party, transport, and accommodation.',
  },
  {
    id: 'event-planning',
    title: 'Event Planning',
    route: '/events',
    targetId: 'event-planning-workspace',
    content: 'The Events page holds setup, readiness, tasks, planning figures, partners, suppliers, and sponsor planning.',
    when: 'Use it while preparing the event before event day.',
    example: 'Add a venue-access task, mark ticket process ready, and track supplier follow-up without changing registration payments.',
  },
  {
    id: 'guests',
    title: 'Guests & Registrations',
    route: '/registrations',
    targetId: 'registrations-workspace',
    content: 'Registrations are buyer or booking records; guests come from the persons attending count and attendee names.',
    when: 'Use this page to add or correct registration records, contacts, group names, payments, and ticket status.',
    example: 'A group booking can be one registration record with four guests.',
  },
  {
    id: 'payments',
    title: 'Registration Payments',
    route: '/payments',
    targetId: 'payments-workspace',
    content: 'Payments tracks guest charges, amount received, balances, payment method, proof, and follow-up status.',
    when: 'Use it when you need to collect balances or clean up registration finance data.',
    example: 'A paid registration with a missing method is internal cleanup, not a reminder audience.',
  },
  {
    id: 'tickets',
    title: 'Tickets',
    route: '/tickets',
    targetId: 'tickets-workspace',
    content: 'Tickets prepares ticket codes and QR access for the selected Working Event.',
    when: 'Use it before event day to assign missing ticket codes and review ticket readiness.',
    example: 'Assign a readable ticket code, then use the QR payload for check-in without exposing guest or payment details.',
  },
  {
    id: 'check-in',
    title: 'Check-In',
    route: '/check-in',
    targetId: 'checkin-workspace',
    content: 'Check-In records event-day attendance from deliberate organizer or scanner action.',
    when: 'Use it at the door to find guests, scan ticket codes, and confirm attendance.',
    example: 'Scanning finds the ticket, then a separate Check In action records attendance.',
  },
  {
    id: 'operations',
    title: 'Operations',
    route: '/operations',
    targetId: 'operations-workspace',
    content: 'Operations tracks event-level income, expenses, refunds, reimbursements, commitments, and adjustments.',
    when: 'Use it for sponsor income, supplier payments, vendor obligations, and event expenses.',
    example: 'Record venue cost here; do not duplicate a guest registration payment as Operations income unless it is intentionally separate.',
  },
  {
    id: 'partners',
    title: 'Partners, Suppliers, and Sponsors',
    route: '/operations',
    targetId: 'operations-workspace',
    content: 'Partners and suppliers are planning and obligation records, separate from registration payment follow-up.',
    when: 'Use them to keep people, companies, and commitments visible for the event team.',
    example: 'Track a sponsor as requested, confirmed cash, or in-kind without treating requested support as received money.',
  },
  {
    id: 'communications',
    title: 'Message Builder',
    route: '/communications',
    targetId: 'message-builder-workspace',
    content: 'Message Builder helps create, personalize, preview, and copy messages. It does not send messages automatically.',
    when: 'Use it when you need text for WhatsApp, email, or another external tool.',
    example: 'Filter unpaid balances, preview the reminder text, copy it, and send it manually outside the app.',
  },
  {
    id: 'reports',
    title: 'Reports',
    route: '/event-review',
    targetId: 'reports-workspace',
    content: 'Reports is read-only review for follow-up, registration payments, Operations, attendance, and event summary.',
    when: 'Use it for event closeout, current-event review, and historical reference.',
    example: 'Review Registration Payments and Operations separately before discussing event financial results.',
  },
  {
    id: 'imports',
    title: 'Import Center',
    route: '/imports',
    targetId: 'imports-workspace',
    content: 'Import Center brings in pasted tables, CSV files, and supported spreadsheets through preview-first review.',
    when: 'Use it when registration data starts in another tool and needs careful duplicate checking.',
    example: 'Confirm the sheet, map headers, review duplicates, then import only approved rows.',
  },
  {
    id: 'settings',
    title: 'Settings',
    route: '/settings',
    targetId: 'settings-workspace',
    content: 'Settings contains practical workspace defaults, access summaries, scanner links, and replay controls.',
    when: 'Use it to review current configuration rather than daily event work.',
    example: 'Copy the scanner link or replay this tutorial from Settings.',
  },
  {
    id: 'system-qa',
    title: 'System QA and Help',
    route: '/qa',
    targetId: 'system-qa-workspace',
    content: 'System QA contains technical checks, safe CODEX_TEST guidance, access boundaries, and production-data protection notes.',
    when: 'Use it for release checks or troubleshooting, not routine event-day flow.',
    example: 'Run read-only checks against CODEX_TEST and confirm CPB stays protected.',
  },
]
